services:
  - type: web
    name: macrotrackr-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --worker-connections 200 --keepalive 15 --max-requests 1000 --max-requests-jitter 100 --timeout 60 app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CHANNEL_ID
        sync: false
